# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mafassi/Downloads/serializer/Serializer/Serialiseur.srcs/sources_1/bd/Design_Serializer/ip/Design_Serializer_xbar_1/Design_Serializer_xbar_1.xci
# IP: The module: 'Design_Serializer_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mafassi/Downloads/serializer/Serializer/Serialiseur.srcs/sources_1/bd/Design_Serializer/ip/Design_Serializer_xbar_1/Design_Serializer_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_Serializer_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/mafassi/Downloads/serializer/Serializer/Serialiseur.srcs/sources_1/bd/Design_Serializer/ip/Design_Serializer_xbar_1/Design_Serializer_xbar_1.xci
# IP: The module: 'Design_Serializer_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mafassi/Downloads/serializer/Serializer/Serialiseur.srcs/sources_1/bd/Design_Serializer/ip/Design_Serializer_xbar_1/Design_Serializer_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_Serializer_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
